name: miniflux-postgres-zhparser

on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every day at 5:30 and 17:30:
    - cron:  '37 17 * * 3'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [13]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            pg_version=${{ matrix.pg_version }}
         # platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE_NAME }}:${{ matrix.pg_version }}-alpine-amd64
